#!/bin/bash
echo -n ' INFRA-START - Starting services for Thinkcube'
#PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:$HOME/bin; export PATH
case "$1" in
start)
	cd /opt/platform/scripts
	sudo python job_processor/daemon.py restart
	sudo python server_monitor/daemon.py restart
        ;;
stop)
        kill -9 `cat /var/run/foobar.pid`
        ;;
*)
        echo "Usage: `basename $0` {start|stop}" >&2
        exit 64
        ;;
esac
exit 0
