#!/bin/bash

# Run this script as root or with sudo

# This script is for post-install for packagers. If you
# use the install script, there is no need to run rhis.

application='cronus_tenants'
http_site="0-${application}"
https_site="0-${application}-ssl"

function prompt_agree(){
    echo "$0 will now attempt to make the following system changes required by $application. It will attempt to:"
    echo "* Enable Apache modules: ssl, rewrite, headers"
    echo "* Enable Apache sites: $http_site, $https_site"
    echo "* Reload Apache configuration"
    echo "* Allow user www-data ALL previleges via sudo"
    echo "* Disable AppArmor"
    echo ""
    echo "Proceed? ( yes | no )"
    read answer
    case $answer
    in
        yes)
        return 0
        ;;
        no)
        return 1
        ;;
        *)
        prompt_agree
    esac
}

if !(prompt_agree); then
  exit 0
fi

echo ""
echo "Enter MySQL username to be used in ${application}:"
read username
echo "Enter MySQL password for ${username}:"
read password

echo "Attempting to write MySQL credentials for Cronus API..."
cd /var/www/cronus-tenants/api/inc/
mv ./config.inc.php ./config.inc.php.tmp
cat ./config.inc.php.tmp | sed -e "s/XXDBUSERXX/${username}/g" | sed -e "s/XXDBPASSWDXX/${password}/g" > ./config.inc.php
rm ./config.inc.php.tmp
cd -

echo "Attempting to write MySQL credentials for Cronus shell..."
cd /opt/cronus/shell
cat shell.inc.sh > shell.inc.sh.tmp
cat shell.inc.sh.tmp | sed -e "s/XXDBUSERXX/${username}/g" | sed -e "s/XXDBPASSWDXX/${password}/g" > shell.inc.sh
rm shell.inc.sh.tmp
cd -

echo "Attempting to enable Apache2 modules: ssl, rewrite, headers..."
a2enmod ssl rewrite headers

echo "Attempting to enable site ${https_site}..."
a2ensite ${https_site}

echo "Attempting to enable site ${http_site}..."
a2ensite ${http_site}

echo "Attempting to reload Apache2 configurations..."
/etc/init.d/apache2 reload

echo "Attempting to add www-data to sodoers..."
echo "www-data  ALL=NOPASSWD:   ALL" >> /etc/sudoers

echo "Attempting to disable AppArmor..."
/etc/init.d/apparmor stop
update-rc.d -f apparmor remove
