#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

#
# Server Restart script for Tenant Server
#

echo 'Starting Tenants Server'
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:$HOME/bin; export PATH
case "$1" in
start)
		FILES="/home/cust*"
		for f in $FILES
		do
				PORT=$(echo basename $f | sed 's/.*[^0-9]\([0-9][0-9]*\).*/\1/g')
		        if [ ! -d /etc/cronus/disabled_customers ];then
           			mkdir -p /etc/cronus/disabled_customers
		        fi
				if [ -f /etc/cronus/disabled_customers/${PORT} ];then
					echo "User $f disabled"
				else
					echo "Starting $f apache server..."
  				# take action on each file. $f store current file name
			 			if [ ! -f $f/etc/apache2/apache2.conf ];then
                			echo "Could not find user apache config"
		        		else
  							/usr/local/sbin/apachectl -f $f/etc/apache2/apache2.conf -k stop
							/bin/sleep 10
  							/usr/local/sbin/apachectl -f $f/etc/apache2/apache2.conf -k start
       		 			fi
					/bin/sleep 10
					echo "Starting $f mysql server"
					ID=`expr ${PORT} - 8080`
					/usr/local/bin/mysqld_multi start ${ID}
					/bin/sleep 90
  			#		/usr/local/sbin/apachectl -f $f/etc/apache2/apache2.conf -k start
				fi
		done
		/bin/sleep 5
        /usr/local/sbin/apachectl -f /usr/local/etc/apache22/httpd.conf -k start
	
	    /bin/sleep 5
        ;;
*)
        echo "Usage: `basename $0` {start}" >&2
        exit 64
        ;;
esac

exit 0
