#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

# Deploy PHP SAML Service

PROGRAM="samlservice"
DEPSCRIPTS=`dirname $0`

PORT=$2
DOMAIN=$3
IDPHOST=$4
IDPCERT=$5

if [ ! $PORT ] || [ ! $DOMAIN ] || [ ! $IDPHOST ] || [ ! $IDPCERT ]; then
    echo "Usage: samlservice {create} {PORT DOMAIN IDPHOST IDPCERT}"
    exit 1
fi

if [[ ! $PORT =~ ^[0-9]{4}$ ]] ; then
    echo "Port out of range"
    exit 1
fi

case $1
in
    create)
        if [ -d /home/cust${PORT}/var/samlservice ] ; then
            rm -r /home/cust${PORT}/var/samlservice
        fi

        cp -r ${DEPSCRIPTS}/deploy-${PROGRAM}/${PROGRAM} /home/cust${PORT}/var/
        cd /home/cust${PORT}/var/${PROGRAM}

        # insert cust domain as entity name for cust samlservice
        mv config/authsources.php config/authsources.php.tmp
        cat config/authsources.php.tmp | sed -e "s/XXXDOMAINXXX/$DOMAIN/g" > config/authsources.php
        rm config/authsources.php.tmp

        # insert IDP metadata for cust samlservice
        mv metadata/saml20-idp-remote.php metadata/saml20-idp-remote.php.tmp
        cat metadata/saml20-idp-remote.php.tmp | sed -e "s/XXXIDPHOSTXXX/$IDPHOST/g" | sed -e "s/XXXIDPCERTXXX/$IDPCERT/g" > metadata/saml20-idp-remote.php
        rm metadata/saml20-idp-remote.php.tmp

        chown -R cust${PORT}:cust${PORT} /home/cust${PORT}/var/samlservice/log
    ;;

    *)
        echo "Usage: samlservice {create|} {PORT DOMAIN IDPHOST IDPCERT}"
        exit 1
esac
