#!/bin/sh -e

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

# Apache 2 virtualize
# Starts multiple instances of Apache2 using different ports.
# https port = http port + 1000
# Usage : apache2 {create|} {8081|8082|8083 etc.}


PROGRAM="apache2"
DEPSCRIPTS=`dirname $0`
APACHE_CONF_DIR=${DEPSCRIPTS}/deploy-${PROGRAM}/etc/apache2

### Linux hosting
#APACHE_CONF='apache2.conf.linux'
#APACHE_STARTUP_SCRIPT='/usr/sbin/apache2ctl'

### BSD hosting
APACHE_CONF='apache2.conf.bsd'
APACHE_STARTUP_SCRIPT='/usr/local/sbin/apachectl'

PORT=$2
SPORT=`expr $2 + 1000`
MYSQLPORT=`expr $2 - 1000`
CHOWN='chown'
TOUCH='touch'

case $1 in
	create)
		if [ ! -d /home/cust${PORT}/etc/apache2 ];then
			mkdir -p /home/cust${PORT}/etc
			mkdir -p /home/cust${PORT}/etc/init.d
			tar xf ${DEPSCRIPTS}/deploy-${PROGRAM}/etc/apache2.tar --directory=/home/cust${PORT}/etc/ 
			cp -a ${DEPSCRIPTS}/deploy-${PROGRAM}/etc/init.d/apache2 /home/cust${PORT}/etc/init.d/
			## todo ##
			## generate SSL certificate and Sign 	
			
	
		fi
		if [ ! -d /home/cust${PORT}/var/lock/apache2 ];then
			mkdir -p /home/cust${PORT}/var/lock/apache2
			mkdir -p /home/cust${PORT}/var/run
		  	${CHOWN} -R cust${PORT}:cust${PORT} /home/cust${PORT}/var/lock/apache2	
		fi
		if [ ! -d /home/cust${PORT}/var/log/apache2 ];then
			mkdir -p /home/cust${PORT}/var/log/apache2
			${TOUCH} /home/cust${PORT}/var/log/apache2/access.log
			${TOUCH} /home/cust${PORT}/var/log/apache2/error.log
		  	chown -R cust${PORT}:cust${PORT} /home/cust${PORT}/var/log	
		fi
		if [ ! -d /home/cust${PORT}/var/www ];then
            mkdir -p /home/cust${PORT}/var/www/cms_website
			chown -R cust${PORT}:cust${PORT} /home/cust${PORT}/var/www
        fi
		cat $APACHE_CONF_DIR/$APACHE_CONF | sed -e "s/NNNN/$PORT/g" | sed -e "s/MMMM/$SPORT/g" > /home/cust${PORT}/etc/apache2/apache2.conf
		cat $APACHE_CONF_DIR/ports.conf | sed -e "s/NNNN/$PORT/g" | sed -e "s/MMMM/$SPORT/g" > /home/cust${PORT}/etc/apache2/ports.conf
		cat $APACHE_CONF_DIR/sites-available/thinkcube | sed -e "s/NNNN/$PORT/g" | sed -e "s/MMMM/$SPORT/g" > /home/cust${PORT}/etc/apache2/sites-available/thinkcube
		cat $APACHE_CONF_DIR/php.ini | sed -e "s/NNNN/$PORT/g" | sed -e "s/SSSS/$MYSQLPORT/g"> /home/cust${PORT}/etc/apache2/php.ini

		# BSD specific
		if [ -d /usr/local/libexec ];then
			ln -s /usr/local/libexec /home/cust${PORT}/etc/apache2/
		fi


		$APACHE_STARTUP_SCRIPT -f /home/cust${PORT}/etc/apache2/apache2.conf -k start
	;;
	*)
		echo "Usage: apache2 {create|} {8081|8082|8083 etc.}"
		exit 1
	;;
esac
