#!/bin/bash

# Run this script as root or with sudo

# This script is for post-install for packagers. If you
# use the install script, there is no need to run rhis.

http_site='0-cronus_infra'
https_site='0-cronus_infra-ssl'

echo "Enabling Apache2 modules: ssl, rewrite, headers..."
a2enmod ssl rewrite headers

echo "Enabling ${https_site}..."
a2ensite ${https_site}

echo "Enabling ${http_site}..."
a2ensite ${http_site}

echo "Reloading Apache2 configurations..."
/etc/init.d/apache2 reload
