#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

DESCRIPTS=`dirname $0`

echo "Creating default-ssl virtual host in /etc/apache2/sites-available"
sudo cp default-ssl.sample /etc/apache2/sites-available/00000-default-ssl
sudo a2ensite /etc/apache2/sites-available
sudo /etc/init.d/apache2 reload

if [ -d /opt/cronus/ ] ; then
    echo "Please Delete directory /opt/cronus to proceed. Exiting"
    #exit 1
fi

echo "Creating directory /opt/cronus"
echo "Copying required scripts to /opt/cronus/shell"
if [ ! -d /opt/cronus/shell ] ; then
    mkdir -p /opt/cronus/shell
fi

cd ../shell
cp -r * /opt/cronus/shell


echo "Enter document root of your webserver"
read doc_root

echo "Copying REST api to ${doc_root}/api"
if [ ! -d /var/www/api ] ; then
    mkdir ${doc_root}/api
fi

cd ../../
cp -r api ${doc_root}

cd infra/rest
cp -r proxy ${doc_root}/api/

echo "Proxy Server successfully installed"
exit 0
