#!/bin/bash

DESCRIPTS=`dirname $0`

if [ -d /opt/cronus/ ] ; then
    echo "Please Delete directory /opt/cronus to proceed. Exiting"
    #exit 1
fi

echo "Creating directory /opt/cronus"
echo "Copying required scripts to /opt/cronus/shell"
if [ ! -d /opt/cronus/shell ] ; then
    sudo mkdir -p /opt/cronus/shell
fi

cd ../apps
sudo cp -r * /opt/cronus/shell

cd ../shell
sudo cp -r * /opt/cronus/shell

echo "Enter document root of your webserver"
read doc_root

echo "Copying REST api to ${doc_root}/api"
if [ ! -d /var/www/api ] ; then
    sudo mkdir ${doc_root}/api
fi

cd ../../
sudo cp -r api ${doc_root}

cd webapp/rest
sudo cp -r tenants ${doc_root}/api/

#echo "Copying Startup script; {tenants_start} to /etc/init.d"
#cd ../scripts
#sudo cp tenants_start /etc/init.d
#sudo update-rc.d tenants_start defaults

echo "Tenants Server successfully installed. Sample IDP  server certificate data is added to /opt/cronus/shell/samlservice/deploy-samlservice/samlservice/metadata/saml20-idp-remote.php. Replace it with your own server certificate data in production environment"
