#!/bin/bash

DESCRIPTS=`dirname $0`

if [ -d /opt/platform/ ] ; then
    echo "Please Delete directory /opt/platform to proceed. Exiting"
    #exit 1
fi

echo "Creating directory /opt/platform"
sudo mkdir /opt/platform

echo "Copying required scripts to /opt/platform/shell"
if [ ! -d /opt/platform/shell ] ; then
    sudo mkdir /opt/platform/shell
fi

cd ../apps
sudo cp -r * /opt/platform/shell

cd ../shell
sudo cp -r * /opt/platform/shell

echo "Enter document root of your webserver"
read doc_root

echo "Copying REST api to ${doc_root}/api"
if [ ! -d /var/www/api ] ; then
    sudo mkdir ${doc_root}/api
fi

cd ../../
sudo cp -r api ${doc_root}

cd webapp/rest
sudo cp -r tenants ${doc_root}/api/

#echo "Copying Startup script; {tenants_start} to /etc/init.d"
#cd ../scripts
#sudo cp tenants_start /etc/init.d
#sudo update-rc.d tenants_start defaults

echo "Tenants Server successfully installed"
exit 0
