#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

#
# Copies API to doc root
#

DESCRIPTS=`dirname $0`

echo "Enter document root of your webserver"
read doc_root

echo "Copying REST api to ${doc_root}/api"
if [ ! -d /var/www/api ] ; then
    sudo mkdir ${doc_root}/api
fi

sudo cp -r ../api ${doc_root}

echo "Replacing Database settings in API"

if [  ! $username ] || [ ! $password ] ; then
    echo "Enter mysql username"
    read username
    echo "Enter mysql password"
    read password
fi

cd ${doc_root}/api/inc/

sudo mv config.inc.php config.inc.php.tmp
sudo cat config.inc.php.tmp | sed -e "s/XXDBUSERXX/${username}/g" | sed -e "s/XXDBPASSiWDXX/${password}/g" > config.inc.php
sudo rm config.inc.php.tmp

cd -
echo "API successfully installed"
