#!/bin/bash

DESCRIPTS=`dirname $0`

echo "Enter document root of your webserver"
read doc_root

echo "Copying REST api to ${doc_root}/api"
if [ ! -d /var/www/api ] ; then
    sudo mkdir ${doc_root}/api
fi

sudo cp -r ../api ${doc_root}

echo "API successfully installed"
exit 0
