#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

# Add a saml consumer in IDP
# usage samlserviceprovider {add|delete} {DOMAIN}

IDP_LOCATION="/var/idp"
DOMAIN=$2

if [ ! -d $IDP_LOCATION ] ; then
    echo "IDP cannot be located at ${IDP_LOCATION}"
    exit 1
fi

if [ ! $DOMAIN ] ; then
    echo "USAGE samlserviceprovider {add|delete} {DOMAIN}"
    exit 1
fi

entry="$""metadata['XXXDOMAINXXX'] = array (
'AssertionConsumerService' => 'https://XXXDOMAINXXX/simplesaml/module.php/saml/sp/saml2-acs.php/sp',
'SingleLogoutService' => 'https://XXXDOMAINXXX/simplesaml/module.php/saml/sp/saml2-logout.php/sp',
);"


case $1
in
    add)
        echo $entry | sed -e "s/XXXDOMAINXXX/${DOMAIN}/g" >> $IDP_LOCATION/metadata/saml20-sp-remote.php
    ;;
    delete)
        mv $IDP_LOCATION/metadata/saml20-sp-remote.php $IDP_LOCATION/metadata/saml20-sp-remote.php.tmp
        sed '/'$DOMAIN'/d' $IDP_LOCATION/metadata/saml20-sp-remote.php.tmp > $IDP_LOCATION/metadata/saml20-sp-remote.php
        rm $IDP_LOCATION/metadata/saml20-sp-remote.php.tmp
    ;;
    *)
    echo "USAGE samlserviceprovider {add|delete} {DOMAIN}"
    exit 1
esac   




