#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

# IDP/LDAP user management
# USAGE: usermgmt {add|delete} {OU} {LDAPUID} [{SN} {USERPASSWORD}]
# 
# Create a file called settings at the same directory level as this script
# Example settings file entries for searchbase dc=thinkcube,dc=net
#  with rootuser admin and root password dirtysecret.
#
# DC1=thinkcube
# DC2=net
# ROOTUSER=admin
# LDAPPASSWD=dirtysecret

DESCRIPTS=`dirname $0`
source $DESCRIPTS/settings


if [ ! $ROOTUSER ] || [ ! $LDAPPASSWD ] || [ ! $DC1 ] || [ ! $DC2 ] ; then
    echo "Missing database settings. Add them in ${DESCRIPTS}/settings"
    exit 1
fi

OU=$2
LDAPUID=$3
SN=$4
CN=$LDAPUID
USERPASSWORD=$5
MAIL=${LDAPUID}@${OU}.${DC1}.${DC2}

SEARCHBASE=dc=${DC1},dc=${DC2}
BINDDN=cn=${ROOTUSER},${SEARCHBASE}

case $1
in
    add)
	echo -e "dn: uid=${LDAPUID},ou=${OU},${SEARCHBASE}\nobjectClass: inetOrgPerson\nuid: ${LDAPUID}\nsn: ${SN}\ncn: ${CN}"\
		"\nuserPassword: ${USERPASSWORD}\nmail: ${MAIL}" | ldapadd -w $LDAPPASSWD -D $BINDDN
	# Whoever calls this must add a password-less user to Zimbra!
    ;;

    delete)
	ldapdelete -w $LDAPPASSWD -D $BINDDN "uid=${LDAPUID},ou=${OU},${SEARCHBASE}"
    ;;

    add-domain)
	echo -e "dn: ou=${OU},${SEARCHBASE}\nobjectClass: organizationalUnit\nou: ${OU}" | ldapadd -w $LDAPPASSWD -D $BINDDN
    ;;

    delete-domain)
	ldapdelete -w $LDAPPASSWD -D $BINDDN -r "ou=${OU},${SEARCHBASE}"
	#Use with care. This can kill baby seals.	
    ;;

    *)
    echo "USAGE: usermgmt {add|delete} {OU} {LDAPUID} [{SN} {USERPASSWORD}]"
    exit 1
esac
