#!/bin/bash

# Cronus is a Multi-Tenant virtualized PaaS solution developed by 
# Thinkcube Systems (Pvt) Ltd. Copyright (C) 2011 Thinkcube Systems (Pvt) Ltd.
#
# This file is part of Cronus.
#
# Cronus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3  
# as published by the Free Software Foundation.
#
# Cronus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cronus. If not; see <http://www.gnu.org/licenses/>.

dbname="cronus"
dbuser="XXDBUSERXX"
dbpasswd="XXDBPASSXX"

server_table="servers"
tenant_table="tenants"
tenant_port_table="tenant_ports"
user_table='tenant_users'
job_table="job_queue"
deployment_table="deployment_queue"

server_types="infra webapp dns idp"

start_port=8805

default_diskquota=20

job_type_tenant_deploy=1
job_type_tenant_destroy=5
job_type_tenant_enable=3
job_type_tenant_disable=4

job_status_new=0
job_status_fail=2
job_status_success=3
job_status_skip=4

deployment_status_new=0

rest_key="ca899e52f5d93bb1cdb623970c894f4cd17eeb3ea752e48a74bbacdb9ef18c08"

IDP_cert="fdfasdfasdfadsfdsaf"
